defmodule GymboWeb.ErrorHTMLTest do
  use GymboWeb.ConnCase, async: true

  import Phoenix.Template

  # Already exists if generated by Phoenix, but add if missing
  test "renders 404.html" do
    assert render_to_string(GymboWeb.ErrorHTML, "404", "html", []) =~ "Not Found"
  end

  test "renders 500.html" do
    assert render_to_string(GymboWeb.ErrorHTML, "500", "html", []) =~ "Internal Server Error"
  end

  test "renders generic error template" do
    assert render_to_string(GymboWeb.ErrorHTML, "custom", "html", []) =~ "Error"
  end
end
